const DataServer = {
  userName: 'Natasha',
  total: 360,
  habits: [
    {
      habitId: 'dsdad121321321dadasd01',
      name: 'workout',
      data: [
        null,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        null,
        null,
        null,
        null,
        true,
        null,
        false,
      ], // 21
      efficiency: '50', // считает бек или фронт?
    },
    {
      habitId: 'fdfsfsdf12321231302',
      name: 'dance every day',
      data: [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        null,
        false,
        null,
        true,
        null,
        null,
        null,
      ], // 21
      efficiency: '70', // считает бек или фронт?
    }, // привычек максимум 10шт
    {
      habitId: 'fdfsfsdf12321251503',
      name: 'drink beer',
      data: [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        null,
        null,
        null,
        false,
        null,
        null,
        true,
      ], // 21
      efficiency: '21', // считает бек или фронт?
    },
    {
      habitId: 'fdfsfsdf123212341404',
      name: 'eat meat',
      data: [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        null,
        true,
        null,
        null,
        null,
        false,
        null,
      ], // 21
      efficiency: '84', // считает бек или фронт?
    },
    {
      habitId: 'fdfsfsdf123212341405',
      name: 'eat meat',
      data: [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        null,
        null,
        null,
        false,
        null,
      ], // 21
      efficiency: '86', // считает бек или фронт?
    },
    {
      habitId: 'fdfsfsdf123212341406',
      name: 'eat meat',
      data: [
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        null,
        true,
        null,
        null,
        null,
        false,
        null,
      ], // 21
      efficiency: '61', // считает бек или фронт?
    },
    {
      habitId: 'fdfsfsdf123212341407',
      name: 'eat meat',
      data: [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        null,
        true,
        null,
        false,
        false,
        false,
        null,
      ], // 21
      efficiency: '90', // считает бек или фронт?
    },
    {
      habitId: 'fdfsfsdf123212341408',
      name: 'eat meat',
      data: [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        null,
        true,
        null,
        null,
        null,
        false,
        null,
      ], // 21
      efficiency: '100', // считает бек или фронт?
    },
    // {
    //   habitId: 'fdfsfsdf123212341409',
    //   name: 'eat meat',
    //   data: [
    //     true,
    //     true,
    //     true,
    //     true,
    //     true,
    //     true,
    //     true,
    //     true,
    //     true,
    //     false,
    //     false,
    //     false,
    //     false,
    //     false,
    //     null,
    //     true,
    //     null,
    //     null,
    //     null,
    //     false,
    //     null,
    //   ], // 21
    //   efficiency: '65', // считает бек или фронт?
    // },
    // {
    //   habitId: 'fdfsfsdf123212341410',
    //   name: 'eat meat',
    //   data: [
    //     true,
    //     true,
    //     true,
    //     true,
    //     true,
    //     true,
    //     true,
    //     true,
    //     true,
    //     false,
    //     false,
    //     false,
    //     false,
    //     false,
    //     null,
    //     true,
    //     null,
    //     null,
    //     null,
    //     false,
    //     null,
    //   ], // 21
    //   efficiency: '65', // считает бек или фронт?
    // }
  ],
};

export default DataServer;
